/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Telinga.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Telinga.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.001']} position={[0, 0, 0.084]} rotation={[0, 0, -Math.PI / 2]} scale={[2.489, 1, 0.633]} />
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.007']} position={[2.164, -1.002, 0.311]} rotation={[0.774, 0.077, -1.053]} scale={[0.517, 0.517, 0.342]} />
      <mesh geometry={nodes.Sphere001.geometry} material={materials['Material.005']} position={[2.164, -1.002, 0.311]} rotation={[0.774, 0.077, -1.053]} scale={[0.517, 0.517, 0.342]} />
      <mesh geometry={nodes.Torus002.geometry} material={materials['Material.008']} position={[3.692, -1.136, 0.48]} rotation={[-2.879, -1.378, 2.008]} scale={0.315} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.008']} position={[3.591, -1.031, 0.408]} rotation={[-0.896, -0.122, -3.044]} scale={[0.093, 0.095, 0.095]} />
      <mesh geometry={nodes.BezierCurve.geometry} material={materials['Material.008']} position={[2.867, 0, 0]} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.003']} position={[0.322, 1.718, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.138, 0.619, 0.144]} />
      <mesh geometry={nodes.Plane003.geometry} material={materials['Material.002']} position={[0.541, 1.452, 0.153]} rotation={[Math.PI / 2, 0, 0]} scale={0.123} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.004']} position={[0.799, 1.357, 0.065]} scale={[0.185, 0.185, 0.163]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.Material} position={[0.799, 1.357, 0.065]} scale={[0.185, 0.185, 0.163]} />
      <mesh geometry={nodes.BezierCurve001.geometry} material={materials['Material.009']} position={[3.601, -1.516, 0.252]} />
      <mesh geometry={nodes.BezierCurve002.geometry} material={materials['Material.009']} position={[4.464, -1.499, 0.314]} />
      <mesh geometry={nodes.Sphere003.geometry} material={materials['Material.006']} position={[3.015, -0.788, 0.266]} rotation={[0, 0, 0.136]} scale={0.547} />
      <mesh geometry={nodes.Sphere004.geometry} material={materials['Material.006']} position={[3.015, -0.788, 0.266]} rotation={[0, 0, 0.136]} scale={0.547} />
      <mesh geometry={nodes.Sphere005.geometry} material={materials['Material.006']} position={[3.015, -0.788, 0.266]} rotation={[0, 0, 0.136]} scale={0.547} />
    </group>
  )
}

useGLTF.preload('/Telinga.glb')
